### ISSUE TITLE
Support json-schema.org Draft4

### ISSUE THREAD

**Issue by seagreen** [timjb/aeson-schema#6]
Are there any plans to add support for draft4? There's a discussion of the draft4 [changes here](http://stackoverflow.com/questions/17205260/json-schema-draft4-vs-json-schema-draft3). I'd be happy to help with such an effort.

**Comment by timjb** [comment]
There are currently no such plans; I lack the time and motivation to continue to develop this library.

**Comment by seagreen** [comment]
I totally understand, thanks so much for writing it in the first place. Feel free to close this issue.

**Comment by dylex** [comment]
Would you accept a PR for this? The only thing I'm not sure about (nor do I really need) is how to retain backwards compatibility with previous versions.

**Comment by seagreen** [comment]
dylex: I wrote [hjsonschema](https://github.com/seagreen/hjsonschema) to support Draft 4, so you also have that option.
